import { SteamUser } from "./steam/steam-user";

export interface Player extends SteamUser {
    index: number;
    client: number;
    playerName: string | null;
    shotsShotgun: number;
    shotsSmg: number;
    shotsSniper: number;
    shotsPistol: number;
    hitsShotgun: number;
    hitsSmg: number;
    hitsSniper: number;
    hitsPistol: number;
    headshotsSmg: number;
    headshotsSniper: number;
    headshotsPistol: number;
    headshotsSiSmg: number;
    headshotsSiSniper: number;
    headshotsSiPistol: number;
    hitsSiShotgun: number;
    hitsSiSmg: number;
    hitsSiSniper: number;
    hitsSiPistol: number;
    hitsTankShotgun: number;
    hitsTankSmg: number;
    hitsTankSniper: number;
    hitsTankPistol: number;
    common: number;
    commonTankUp: number;
    siKilled: number;
    siKilledTankUp: number;
    siDamage: number;
    siDamageTankUp: number;
    incaps: number;
    died: number;
    skeets: number;
    skeetsHurt: number;
    skeetsMelee: number;
    levels: number;
    levelsHurt: number;
    pops: number;
    crowns: number;
    crownsHurt: number;
    shoves: number;
    deadStops: number;
    tongueCuts: number;
    selfClears: number;
    fallDamage: number;
    dmgTaken: number;
    ffGiven: number;
    ffTaken: number;
    ffHits: number;
    tankDamage: number;
    witchDamage: number;
    meleesOnTank: number;
    rockSkeets: number;
    rockEats: number;
    ffGivenPellet: number;
    ffGivenBullet: number;
    ffGivenSniper: number;
    ffGivenMelee: number;
    ffGivenFire: number;
    ffGivenIncap: number;
    ffGivenOther: number;
    ffGivenSelf: number;
    ffTakenPellet: number;
    ffTakenBullet: number;
    ffTakenSniper: number;
    ffTakenMelee: number;
    ffTakenFire: number;
    ffTakenIncap: number;
    ffTakenOther: number;
    ffGivenTotal: number;
    ffTakenTotal: number;
    clears: number;
    avgClearTime: number;
    timeStartPresent: Date;
    timeStopPresent: Date;
    timePresentElapsed: string | null;
    timeStartAlive: Date;
    timeStopAlive: Date;
    timeAliveElapsed: string | null;
    timeStartUpright: Date;
    timeStopUpright: Date;
    timeUprightElapsed: string | null;
}